[package]
name = "telegram"
version = "0.0.1"
edition = "2021"

[[example]]
name = "bot"
path = "examples/bot.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
structopt = "0.3.26"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
cargo-edit = "0.12.2"
