[package]
name = "telegram"
version = "0.0.1"
edition = "2021"

[[example]]
name = "bot"
path = "examples/bot.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-edit = "0.12.2"
structopt = "0.3.26"
