[package]
name = "telegram"
edition = "2021"
version = "0.0.1"
talegram-version = "7.0"

[[example]]
name = "bot"
path = "examples/bot.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = {  version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
structopt = "0.3.26"
tokio = { version = "1", features = ["full"] }


[dev-dependencies]
cargo-edit = "0.12.2"
