name: Rust
on: push 

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy --all-targets --all-features
      - name: Build
        run: cargo build --verbose
      - name: Tests
        run: cargo test --verbose
